### ISSUE TITLE
Usar bracketSameLine

### ISSUE THREAD

**Issue by italomz** [comunicain/pattern.in#3]
Minha sugestão seria usar bracketSameLine como 'true'. Ficaria assim: 
![image](https://user-images.githubusercontent.com/100162319/165297801-3527d655-2eba-4c7c-98eb-4273e447f7bf.png)
(true)
![image](https://user-images.githubusercontent.com/100162319/165297867-aea9237d-a5b2-4fdb-9d3e-be13d3b567e0.png)
(false)

**Comment by sasknot** [comment]
Para mim acredito ficar um pouco estranho, não sei ficaria fácil saber quando um elemento pai termina seus atributos e começa os elementos filhos. Tem um detalhe também que se for tentar duplicar a última linha (que tem o `>` de fechamento) vai dar erro e precisa de intervenção manual, o que para mim não acho que seria um empecilho.

Mostrando outros exemplos retirados do `src/components/Editor.vue` projeto `portal` implementando essa regra:

![Screen Shot 2022-04-26 at 09 40 53](https://user-images.githubusercontent.com/232754/165304375-edf2927d-ea53-4fc8-a984-b30ea8cae543.png)
![Screen Shot 2022-04-26 at 09 41 11](https://user-images.githubusercontent.com/232754/165303987-3eabd095-3d4b-4f93-8ee4-961b704407a0.png)
![Screen Shot 2022-04-26 at 09 41 37](https://user-images.githubusercontent.com/232754/165304002-a61aa58d-ad15-48ec-8071-ed09a7454b24.png)
![Screen Shot 2022-04-26 at 09 41 53](https://user-images.githubusercontent.com/232754/165304018-b20522db-8498-4be9-85fd-e21d7dbe3c62.png)

**Comment by italomz** [comment]
Faz sentido, concordo com vc. 
Quando pensei em deixar na mesma linha, o objetivo seria poupar uma nova linha só com um caracter a mais e quando há mtas tags, fica visualmente estranho.

**Comment by sasknot** [comment]
@italomz nos prints 2 e 4 ficou bom essa abordagem, mas nos prints 1 e 3 eu acredito que ficaram um pouco difíceis de ler. Pode ser devido ao fato da linha ser extensa horizontalmente...

**Comment by brunocomunicain** [comment]
@sasknot sim, precisa ter um limite de linha para que fique fácil ler ela por completa ao invés de fazer o scroll horizontal. @italomz eu acho que eu prefiro como **false** por causa do esquema de quando for adicionar algo no final voc teria que intervir manualmente a quebra.

**Comment by italomz** [comment]
Entendido, realmente esses pontos são bastante válidos.
